### ISSUE TITLE
'h_addr' hatasi

### ISSUE THREAD

**Issue by mozgan** [EnderUNIX/Aget#1]
Bazi *NIX sistemlerde (örnegin Mac OS) 'hostent' yapisi icerisinde kullanilan 'h_addr_list' icin bir yapi tanimlanmamistir. Bu problemi cözmek icin Head.h icerisine asagidaki kod eklenebilir:
# ifndef h_addr
# define h_addr h_addr_list[0]
# endif

patch:
index 215c2af..84465be 100644
--- a/Head.h
+++ b/Head.h
@@ -3,6 +3,10 @@

 #include "Data.h"

+#ifndef h_addr
+#define h_addr h_addr_list[0]
+#endif
+
 void http_head_req(struct request *);

 #endif

**Comment by bemre** [comment]
tesekkurler yama uygulandı.
